# Generated by Django 2.0.2 on 2019-04-01 22:26

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.IntegerField()),
                ('body', models.TextField()),
                ('search_vector', django.contrib.postgres.search.SearchVectorField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='searchentity',
            unique_together={('entity_type', 'entity_id')},
        ),
    ]
