# Generated by Django 2.0.2 on 2019-04-01 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория обращения',
                'verbose_name_plural': 'Категории обращения',
            },
        ),
        migrations.CreateModel(
            name='FeedbackItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.EmailField(max_length=254, verbose_name='E-mail автора обращения')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема обращения')),
                ('text', models.TextField(verbose_name='Текст обращения')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время обращения')),
                ('is_seen', models.BooleanField(default=False, verbose_name='Просмотренно')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.CategoryFeedback', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Обращение к разработчику',
                'verbose_name_plural': 'Обращения к разработчику',
            },
        ),
        migrations.CreateModel(
            name='InCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail отвественного за обращения')),
            ],
            options={
                'verbose_name': 'Ответственный за обращения',
            },
        ),
    ]
