# Generated by Django 2.0.2 on 2019-04-01 22:26

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
        ('attachment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=255, verbose_name='Отчество')),
                ('info', models.TextField(verbose_name='Направление курсов')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('order', models.PositiveIntegerField(default=0)),
                ('gi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.GiItem', verbose_name='ГИ')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attachment.Attachment', verbose_name='Фото')),
                ('si', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='gi', chained_model_field='gi', null=True, on_delete=django.db.models.deletion.CASCADE, sort=False, to='activity.SiItem', verbose_name='СИ')),
            ],
            options={
                'verbose_name': 'Эксперт',
                'verbose_name_plural': 'Эксперты',
                'ordering': ('order',),
            },
        ),
    ]
