# Generated by Django 2.0.2 on 2019-04-01 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recourse', '0001_initial'),
        ('expert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recourse.Specialty', verbose_name='Специализация эксперта'),
        ),
    ]
