# Generated by Django 2.0.2 on 2019-04-01 22:26

from django.db import migrations, models
import django.db.models.deletion
import vkrb.search


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст статьи')),
                ('keywords', models.TextField(blank=True, help_text='Через пробел', null=True, verbose_name='Ключевые слова')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
            bases=(vkrb.search.SearchModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ArticleAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_attachments', to='digest.Article', verbose_name='Статья')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attachment.Attachment', verbose_name='Прикрепление')),
            ],
            options={
                'verbose_name': 'Прикрепление',
                'verbose_name_plural': 'Прикрепления',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Digest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Дайджест',
                'verbose_name_plural': 'Дайджесты',
                'ordering': ('order',),
            },
            bases=(vkrb.search.SearchModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DigestCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория дайджеста',
                'verbose_name_plural': 'Категории дайджестов',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='digest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digest.DigestCategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='digest',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icon', to='attachment.Attachment', verbose_name='Фото дайджеста'),
        ),
        migrations.AddField(
            model_name='digest',
            name='pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attachment.Attachment', verbose_name='PDF'),
        ),
        migrations.AddField(
            model_name='article',
            name='attachments',
            field=models.ManyToManyField(through='digest.ArticleAttachment', to='attachment.Attachment', verbose_name='Прикрепления'),
        ),
        migrations.AddField(
            model_name='article',
            name='digest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digest.Digest', verbose_name='Дайджест'),
        ),
    ]
