# Generated by Django 2.0.2 on 2019-04-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_changes', models.BooleanField(default=False, verbose_name='Запретить изменение всех профилей')),
            ],
            options={
                'verbose_name': 'Глобальные настройки',
            },
        ),
    ]
