# Generated by Django 2.0.2 on 2019-04-01 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChanged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Новый возраст')),
                ('experience', models.IntegerField(blank=True, null=True, verbose_name='Новый стаж в компании')),
                ('occupations', models.TextField(blank=True, null=True, verbose_name='Новый род деятельности')),
                ('interests', models.TextField(blank=True, null=True, verbose_name='Новые интересные темы')),
                ('phone', models.CharField(default=None, max_length=20, null=True, verbose_name='Новый телефон')),
                ('first_name', models.CharField(max_length=30, verbose_name='Новое имя')),
                ('last_name', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Новая фамилия')),
                ('company', models.CharField(default=None, max_length=255, null=True, verbose_name='Новая компания')),
                ('location', models.CharField(default=None, max_length=255, null=True, verbose_name='Новое местонахождение')),
                ('status', models.CharField(choices=[('approved', 'Подтвержден'), ('rejected', 'Отклонен'), ('unchecked', 'Не рассмотрен')], default='unchecked', max_length=10, verbose_name='Статус заявки на изменение профиля')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Причина отклонения')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_status_set', models.BooleanField(default=False)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attachment.Attachment', verbose_name='Новое фото')),
                ('user', models.ForeignKey(blank=True, default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос на измененные данных пользователя',
                'verbose_name_plural': 'Запросы на измененные данных пользователей',
            },
        ),
    ]
