# Generated by Django 2.0.2 on 2019-04-01 22:26

from django.db import migrations, models
import vkrb.attachment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Форматы: .jpg .png .pdf', upload_to=vkrb.attachment.models.content_file_name, validators=[vkrb.attachment.models.validate_file_type], verbose_name='Файл')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Прикрепление',
                'verbose_name_plural': 'Прикрепления',
            },
        ),
    ]
