# Generated by Django 2.0.2 on 2019-04-01 22:26

from django.db import migrations, models
import django.db.models.deletion
import vkrb.search


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('acronym', models.CharField(max_length=255, null=True, verbose_name='Аббревиатура ГИ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('link', models.URLField(max_length=1000, null=True, verbose_name='Ссылка')),
                ('lat', models.FloatField(null=True, verbose_name='Широта')),
                ('lng', models.FloatField(null=True, verbose_name='Долгота')),
                ('specialty', models.CharField(blank=True, max_length=255, null=True, verbose_name='Специализация')),
                ('ceo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Генеральный директор')),
                ('activity_course', models.TextField(blank=True, null=True, verbose_name='Ключевые направления деятельности')),
                ('history', models.TextField(blank=True, null=True, verbose_name='Историческая справка')),
                ('contact_info', models.TextField(blank=True, null=True, verbose_name='Контактная информация')),
                ('is_actual', models.BooleanField(default=True)),
                ('pdf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gi_pdf', to='attachment.Attachment', verbose_name='PDF')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attachment.Attachment', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'ГИ',
                'verbose_name_plural': 'ГИ',
            },
            bases=(vkrb.search.SearchModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SiItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('acronym', models.CharField(max_length=255, null=True, verbose_name='Аббревиатура СИ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('link', models.URLField(max_length=1000, verbose_name='Ссылка')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lng', models.FloatField(verbose_name='Долгота')),
                ('specialty', models.CharField(blank=True, max_length=255, null=True, verbose_name='Специализация')),
                ('ceo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Генеральный директор')),
                ('contact_info', models.TextField(blank=True, null=True, verbose_name='Контактная информация')),
                ('activity_course', models.TextField(blank=True, null=True, verbose_name='Ключевые направления деятельности')),
                ('history', models.TextField(blank=True, null=True, verbose_name='Историческая справка')),
                ('gi', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='activity.GiItem', verbose_name='ГИ')),
                ('pdf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='si_pdf', to='attachment.Attachment', verbose_name='PDF')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attachment.Attachment', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'СИ',
                'verbose_name_plural': 'СИ',
            },
            bases=(vkrb.search.SearchModelMixin, models.Model),
        ),
    ]
