# Generated by Django 2.0.2 on 2019-05-19 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giitem',
            options={'verbose_name': 'Факультет', 'verbose_name_plural': 'Факультеты'},
        ),
        migrations.AlterModelOptions(
            name='siitem',
            options={'verbose_name': 'кафедра', 'verbose_name_plural': 'кафедры'},
        ),
        migrations.AlterField(
            model_name='giitem',
            name='acronym',
            field=models.CharField(max_length=255, null=True, verbose_name='Аббревиатура факультета'),
        ),
        migrations.AlterField(
            model_name='giitem',
            name='ceo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Декан факультета'),
        ),
        migrations.AlterField(
            model_name='giitem',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='giitem',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='siitem',
            name='acronym',
            field=models.CharField(max_length=255, null=True, verbose_name='Аббревиатура кафедры'),
        ),
        migrations.AlterField(
            model_name='siitem',
            name='ceo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='заведующий кафедрой'),
        ),
        migrations.AlterField(
            model_name='siitem',
            name='gi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.GiItem', verbose_name='ГИ'),
        ),
        migrations.AlterField(
            model_name='siitem',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='siitem',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='siitem',
            name='pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='si_pdf', to='attachment.Attachment', verbose_name='PDF'),
        ),
    ]
