# Generated by Django 2.0.2 on 2019-05-21 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20190519_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siitem',
            name='gi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.GiItem', verbose_name='Факультет'),
        ),
    ]
