# Generated by Django 2.0.2 on 2019-05-22 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20190521_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giitem',
            name='pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gi_pdf', to='attachment.Attachment', verbose_name='PDF'),
        ),
    ]
