# Generated by Django 2.0.2 on 2019-04-01 22:26

from django.db import migrations, models
import vkrb.search


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('about_knpk', 'О КНПК')], max_length=255, unique=True, verbose_name='Тип текста')),
                ('content', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Текст',
                'verbose_name_plural': 'Текста',
            },
            bases=(vkrb.search.SearchModelMixin, models.Model),
        ),
    ]
