# Generated by Django 2.0.2 on 2019-04-01 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import vkrb.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('phone', models.CharField(default=None, max_length=20, null=True, verbose_name='Телефон')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Фамилия')),
                ('company', models.CharField(default=None, max_length=255, null=True, verbose_name='Компания')),
                ('location', models.CharField(default=None, max_length=255, null=True, verbose_name='Место нахождения')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('experience', models.IntegerField(blank=True, null=True, verbose_name='Стаж в компании')),
                ('occupations', models.TextField(blank=True, null=True, verbose_name='Род деятельности')),
                ('interests', models.TextField(blank=True, null=True, verbose_name='Интересные темы')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_blocked', models.BooleanField(default=False, help_text='Указывает на возможность изменения профиля', verbose_name='Блокировка редактирования профиля')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', vkrb.core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(default=None, max_length=255, null=True)),
                ('device_type', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], default='ios', max_length=10)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
