# Generated by Django 2.0.2 on 2019-05-22 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20190523_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sciencearticle',
            name='attachment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='attachment_articles', to='attachment.Attachment', verbose_name='Приложение'),
        ),
    ]
