# Generated by Django 2.0.2 on 2019-04-01 22:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import vkrb.search


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachemntInNewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.BooleanField(default=False, help_text='Рекомендуемое соотношение сторон для главного фото 4:4', verbose_name='Главное фото')),
                ('order', models.PositiveIntegerField(default=0)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='attachment.Attachment', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'db_table': 'attachment_newsitem',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='CategoryNewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название категории')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'категория новости',
                'verbose_name_plural': 'категории новостей',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации новости')),
                ('keywords', models.TextField(blank=True, help_text='Через пробел', null=True, verbose_name='Ключевые слова')),
                ('attachments', models.ManyToManyField(through='newsitem.AttachemntInNewsItem', to='attachment.Attachment', verbose_name='Фото')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsitem.CategoryNewsItem', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
            bases=(vkrb.search.SearchModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='attachemntinnewsitem',
            name='newsitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsitem.NewsItem', verbose_name='Новость'),
        ),
    ]
