# Generated by Django 2.0.2 on 2019-05-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsitem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Ключевое слово',
                'verbose_name_plural': 'Ключевые слова',
            },
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='keywords',
        ),
        migrations.AddField(
            model_name='newsitem',
            name='keywords',
            field=models.ManyToManyField(blank=True, null=True, to='newsitem.NewsKeyword', verbose_name='Ключевые слова'),
        ),
    ]
