# Generated by Django 2.0.2 on 2019-05-22 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsitem', '0002_auto_20190522_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='category',
        ),
    ]
