# Generated by Django 2.0.2 on 2019-05-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsitem', '0003_remove_newsitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newskeyword',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
